#!/bin/bash

# Creates a list of all test files and directories from wacc_examples
function create_test_list() {
	find wacc_examples -type f -exec echo "'{}'" >> test_list \;
}

# Creates an identical list, in csv with appended expected exit codes
function create_exit_codes_list() {
	while read in; do 
		# output="$(refCompile -s $in)"
		output="$(cat $in)"
		
		syntax_error=$(echo "$output" | grep "#syntax_error#" | wc -l)
		semantic_error=$(echo "$output" | grep "#semantic_error#" | wc -l)
	
		echo -n "$in," >> test_list_exit_codes
	
		if [ $syntax_error -eq 1 ]
		then
			echo 100 >> test_list_exit_codes
		elif [ $semantic_error -eq 1 ]
		then
			echo 200 >> test_list_exit_codes
		else
			echo 0 >> test_list_exit_codes
		fi
	done < test_list
}

read_exit_codes
