stages:       # List of stages for jobs, and their order of execution
  - build
  - test
  - release

build-job:    # This job runs in the build stage, which runs first.
  stage: build
  script:
    - docker build -t wacc-compiler-build:${CI_COMMIT_SHORT_SHA} --target builder .

test-job:     # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  script:
    - docker build -t wacc-compiler-test:${CI_COMMIT_SHORT_SHA} --target test .
    - docker run wacc-compiler-test:${CI_COMMIT_SHORT_SHA}

release-job:
  stage: release
  script:
    - docker build -t \
          gitlab.doc.ic.ac.uk:4567/lab2122_spring/wacc_32:${CI_COMMIT_SHORT_SHA} \
          --target release .
    - docker push gitlab.doc.ic.ac.uk:4567/lab2122_spring/wacc_32:${CI_COMMIT_SHORT_SHA}
